version: '3.8'

services:
  app:
    build: .
    ports:
      - "8003:8003"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=vwings24x7_db
    networks:
      - vwings_app_backend_net

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: vwings24x7_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "8005:8005"

    networks:
      - vwings_app_backend_net

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: "False"
      PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT: "False"
      PGADMIN_CONFIG_PROXY_X_HOST_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_FOR_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_PROTO_COUNT: "1"
    ports:
      - "8004:80"
    depends_on:
      - postgres
    networks:
      - vwings_app_backend_net

volumes:
  postgres_data:


networks:
  vwings_app_backend_net:
    driver: bridge
    ipam:
      config:
        # Using 10.x.x.x avoids the crowded 172.x.x.x space
        - subnet: 10.50.0.0/24
